const veggies = ['Apple', 'Apricot', 'Avocado', 'Banana', 'Bilberry', 'Blackberry', 'Blackcurrant', 'Blueberry', 'Boysenberry', 'Cherry', 'Cherimoya', 'Cloudberry', 'Coconut', 'Cranberry', 'Damson', 'Dragonfruit', 'Durian', 'Elderberry', 'Feijoa', 'Fig', 'Gooseberry', 'Grape', 'Raisin', 'Grapefruit', 'Guava', 'Honeyberry', 'Huckleberry', 'Jabuticaba', 'Jackfruit', 'Jambul', 'Kiwano', 'Kiwifruit', 'Kumquat', 'Lemon', 'Lime', 'Loquat', 'Longan', 'Lychee', 'Mango', 'Mangosteen', 'Marionberry', 'Melon', 'Cantaloupe', 'Watermelon', 'Mulberry', 'Nectarine', 'Orange', 'Clementine', 'Tangerine', 'Papaya', 'Passionfruit', 'Peach', 'Pear', 'Persimmon', 'Plum', 'Pineapple', 'Pomegranate', 'Pomelo', 'Quince', 'Raspberry', 'Salmonberry', 'Rambutan', 'Redcurrant', 'Salak', 'Satsuma', 'Soursop', 'Strawberry', 'Tamarillo', 'Tamarind', 'Artichoke', 'Arugula', 'Asparagus', 'Legumes', 'Lentils', 'Peas', 'Mangetout', 'Broccoli', 'Cabbage', 'Cauliflower', 'Celery', 'Chard', 'Endive', 'Frisee', 'Fennel', 'Anise', 'Basil', 'Caraway', 'Dill', 'Fennel', 'Marjoram', 'Oregano', 'Parsley', 'Rosemary', 'Sage', 'Thyme', 'Kohlrabi', 'Onion', 'Chives', 'Garlic', 'Parsley', 'Pepper', 'Chili', 'Paprika', 'Radicchio', 'Rhubarb', 'Beetroot', 'Carrot', 'Celeriac', 'Daikon', 'Ginger', 'Parsnip', 'Rutabaga', 'Radish', 'Spinach', 'Zucchini', 'Cucumber', 'Pumpkin', 'Tomato', 'Potato'];
const colors = ['Amber', 'Amethyst', 'Aquamarine', 'Awesome', 'Azure', 'Begonia', 'Beige', 'Black', 'Blue', 'Bronze', 'Brown', 'Burgundy', 'Canary', 'Caramel', 'Cherry', 'Coral', 'Cyan', 'Emerald', 'Gold', 'Green', 'Indigo', 'Jade', 'Magenta', 'Mint', 'Mustard', 'Navy', 'Olive', 'Opal', 'Orange', 'Pink', 'Pistachio', 'Red', 'Rose', 'Ruby', 'Salmon', 'Sapphire', 'Scarlet', 'Sepia', 'Silver', 'Turquoise', 'Ultramarine', 'Vermilion', 'Violet', 'White', 'Yellow'];

export function tableNameByAddress(address) {
  const veggieIdx = parseInt(address.substr(2, 6), 16) % veggies.length;
  const colorIdx = parseInt(address.substr(12, 6), 16) % colors.length;

  return `${colors[colorIdx]} ${veggies[veggieIdx]}`;
}
