language: node_js
node_js:
  - 7.4.0
before_script:
  - npm install
script:
  - npm test
  - npm run build
notifications:
  email:
    recipients:
      - info@acebusters.com
    on_success: change
    on_failure: always